site_name: Find The Items
site_url: https://meteorbee.github.io/FindTheItems
site_description: The documentation for the Find The Items kit by meteorbee!
site_author: meteorbee

repo_name: meteorbee/FindTheItems
repo_url: https://github.com/meteorbee/FindTheItems
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.path
    - content.tooltips
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: black
      accent: indigo
nav:
  - Home: index.md

  - Documentation:
    - Getting Started:
      - Installation: GettingStarted/installation.md
      - Making an item: GettingStarted/making-an-item.md
      - Making custom pickup logic: GettingStarted/making-custom-pickup-logic.md
      - Making menu items: GettingStarted/making-menu-items.md
      - Making fast travel points: GettingStarted/making-fast-travel-points.md
      - Making realms: GettingStarted/making-realms.md
      - Sendoff: GettingStarted/sendoff.md

    - API Reference:
      - FindTheItems:
        - FindTheItems.new(): APIReference/FindTheItems/new.md
        - FindTheItems:InitializeItemsIn(): APIReference/FindTheItems/initializeitemsin.md
        - FindTheItems:GiveItem(): APIReference/FindTheItems/giveitem.md
        - FindTheItems:SetStat(): APIReference/FindTheItems/setstat.md
        - FindTheItems:GetStat(): APIReference/FindTheItems/getstat.md
        - FindTheItems:AddToStat(): APIReference/FindTheItems/addtostat.md
        - FindTheItems:SetupResources(): APIReference/FindTheItems/setupresources.md
      - ClientModule:
        - ClientModule.Init(): APIReference/ClientModule/init.md

    - Types:
        - FindTheItems: Types/findtheitems.md
        - Item: Types/item.md

  - About:
    - Capabilities: About/capabilities.md
    - Patch Notes: About/changelogs.md
plugins:
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
extra_css:
  - stylesheets/colors.css